create table public.daily_analysis_usage (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, usage_date date not null, status text not null check(status in ('reserved','completed')), expires_at timestamptz not null, completed_at timestamptz, created_at timestamptz not null default now(), constraint daily_analysis_usage_completion_check check ((status='reserved' and completed_at is null) or (status='completed' and completed_at is not null)));
create index daily_analysis_usage_lookup_idx on public.daily_analysis_usage(user_id,usage_date,status,expires_at);
alter table public.daily_analysis_usage enable row level security;
revoke all on table public.daily_analysis_usage from anon, authenticated;
grant select,insert,update,delete on public.daily_analysis_usage to service_role;

create function public.analysis_quota_time(p_at timestamptz) returns table(usage_date date,reset_at timestamptz) language sql immutable security invoker set search_path='' as $$ select (p_at at time zone 'Asia/Taipei')::date,(((p_at at time zone 'Asia/Taipei')::date+1)::timestamp at time zone 'Asia/Taipei'); $$;

create function public.get_daily_analysis_quota(p_user_id uuid) returns table(limit_count integer,used_count integer,reserved_count integer,remaining_count integer,available_now_count integer,reset_at timestamptz) language plpgsql security invoker set search_path='' as $$ declare t record; n timestamptz:=now(); begin select * into t from public.analysis_quota_time(n); select count(*) filter(where status='completed'),count(*) filter(where status='reserved' and expires_at>n) into used_count,reserved_count from public.daily_analysis_usage where user_id=p_user_id and usage_date=t.usage_date; limit_count:=3; used_count:=coalesce(used_count,0); reserved_count:=coalesce(reserved_count,0); remaining_count:=greatest(0,3-used_count); available_now_count:=greatest(0,3-used_count-reserved_count); reset_at:=t.reset_at; return next; end $$;

create function public.reserve_daily_analysis(p_user_id uuid,p_reservation_id uuid) returns table(outcome text,reservation_id uuid,limit_count integer,used_count integer,reserved_count integer,remaining_count integer,available_now_count integer,reset_at timestamptz) language plpgsql security invoker set search_path='' as $$ declare t record; n timestamptz:=now(); q record; begin select * into t from public.analysis_quota_time(n); perform pg_advisory_xact_lock(hashtextextended(p_user_id::text||':'||t.usage_date::text,0)); delete from public.daily_analysis_usage where user_id=p_user_id and usage_date=t.usage_date and status='reserved' and expires_at<=n; if exists(select 1 from public.daily_analysis_usage where id=p_reservation_id and user_id=p_user_id and usage_date=t.usage_date) then outcome:='reserved'; else select * into q from public.get_daily_analysis_quota(p_user_id); if q.used_count>=3 then outcome:='daily_limit_reached'; elsif q.used_count+q.reserved_count>=3 then outcome:='slots_busy'; else insert into public.daily_analysis_usage(id,user_id,usage_date,status,expires_at) values(p_reservation_id,p_user_id,t.usage_date,'reserved',n+interval '2 minutes'); outcome:='reserved'; end if; end if; select * into q from public.get_daily_analysis_quota(p_user_id); reservation_id:=p_reservation_id; limit_count:=q.limit_count;used_count:=q.used_count;reserved_count:=q.reserved_count;remaining_count:=q.remaining_count;available_now_count:=q.available_now_count;reset_at:=q.reset_at; return next; end $$;

create function public.complete_daily_analysis(p_user_id uuid,p_reservation_id uuid) returns table(outcome text,reservation_id uuid,limit_count integer,used_count integer,reserved_count integer,remaining_count integer,available_now_count integer,reset_at timestamptz) language plpgsql security invoker set search_path='' as $$ declare r public.daily_analysis_usage%rowtype; q record; changed integer; begin select * into r from public.daily_analysis_usage where id=p_reservation_id; if not found or r.user_id<>p_user_id then outcome:='invalid_reservation'; else perform pg_advisory_xact_lock(hashtextextended(p_user_id::text||':'||r.usage_date::text,0)); select * into r from public.daily_analysis_usage where id=p_reservation_id and user_id=p_user_id for update; if not found then outcome:='invalid_reservation'; elsif r.status='completed' then outcome:='completed'; elsif r.expires_at<=now() then outcome:='expired_reservation'; else update public.daily_analysis_usage set status='completed',completed_at=now() where id=p_reservation_id and user_id=p_user_id and status='reserved' and expires_at>now(); get diagnostics changed=row_count; outcome:=case when changed=1 then 'completed' else 'invalid_reservation' end; end if; end if; select * into q from public.get_daily_analysis_quota(p_user_id); reservation_id:=p_reservation_id;limit_count:=q.limit_count;used_count:=q.used_count;reserved_count:=q.reserved_count;remaining_count:=q.remaining_count;available_now_count:=q.available_now_count;reset_at:=q.reset_at;return next;end $$;

create function public.release_daily_analysis(p_user_id uuid,p_reservation_id uuid) returns text language plpgsql security invoker set search_path='' as $$ declare r public.daily_analysis_usage%rowtype; changed integer; begin select * into r from public.daily_analysis_usage where id=p_reservation_id; if not found then return 'released'; end if; perform pg_advisory_xact_lock(hashtextextended(p_user_id::text||':'||r.usage_date::text,0)); select * into r from public.daily_analysis_usage where id=p_reservation_id for update; if not found then return 'released'; end if; if r.user_id<>p_user_id then return 'invalid_reservation'; end if; if r.status='completed' then return 'already_completed'; end if; delete from public.daily_analysis_usage where id=p_reservation_id and user_id=p_user_id and status='reserved'; get diagnostics changed=row_count; return case when changed=1 then 'released' else 'invalid_reservation' end; end $$;

revoke all on function public.analysis_quota_time(timestamptz),public.get_daily_analysis_quota(uuid),public.reserve_daily_analysis(uuid,uuid),public.complete_daily_analysis(uuid,uuid),public.release_daily_analysis(uuid,uuid) from public,anon,authenticated;
grant execute on function public.analysis_quota_time(timestamptz),public.get_daily_analysis_quota(uuid),public.reserve_daily_analysis(uuid,uuid),public.complete_daily_analysis(uuid,uuid),public.release_daily_analysis(uuid,uuid) to service_role;
